### ISSUE TITLE
LESS Convert SCSS

### ISSUE THREAD

**Issue by LinBoLen** [ng-zorro-fork/ng-zorro-ui#5]
| Method | Less | Scss |
| ------ | ---- | ---- |
| fade   |      |      |
|        |      |      |
|        |      |      |

**Comment by LinBoLen** [comment]
hate BEM or CIB. wants never touch it

**Comment by LinBoLen** [comment]
```scss
@at-root &,
  & a,
  & a:hover {
    color: $tag-default-color;
  }
```

```less
  &,
  a,
  a:hover {
    color: $tag-default-color;
  }
```
